import { Shoe } from '@/types/shoe';

// Using Unsplash source for realistic shoe/sneaker imagery
// In production these come from Airtable attachments
export const MOCK_SHOES: Shoe[] = [
  {
    id: '1',
    name: 'Chennai Streets AF1',
    brand: 'Nike',
    type: 'Low-top',
    themes: ['Tamil Culture', 'Streetwear'],
    imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80',
    aspectRatio: 'tall',
    tags: ['white', 'custom', 'kolam'],
    featured: true,
  },
  {
    id: '2',
    name: 'Graffiti Boost',
    brand: 'Adidas',
    type: 'High-top',
    themes: ['Graffiti', 'Streetwear'],
    imageUrl: 'https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=600&q=80',
    aspectRatio: 'square',
    tags: ['black', 'spray paint', 'urban'],
    featured: true,
  },
  {
    id: '3',
    name: 'Vintage Woven',
    brand: 'New Balance',
    type: 'Low-top',
    themes: ['Vintage', 'Retro'],
    imageUrl: 'https://images.unsplash.com/photo-1539185441755-769473a23570?w=600&q=80',
    aspectRatio: 'wide',
    tags: ['cream', 'retro', 'woven'],
    featured: false,
  },
  {
    id: '4',
    name: 'Floral Jordan',
    brand: 'Jordan',
    type: 'High-top',
    themes: ['Floral', 'Abstract'],
    imageUrl: 'https://images.unsplash.com/photo-1556906781-9a412961d28e?w=600&q=80',
    aspectRatio: 'tall',
    tags: ['red', 'floral', 'bold'],
    featured: true,
  },
  {
    id: '5',
    name: 'Anime Chuck',
    brand: 'Converse',
    type: 'High-top',
    themes: ['Anime', 'Streetwear'],
    imageUrl: 'https://images.unsplash.com/photo-1607522370275-f14206abe5d3?w=600&q=80',
    aspectRatio: 'square',
    tags: ['black', 'anime', 'canvas'],
    featured: false,
  },
  {
    id: '6',
    name: 'Kolam Ghost',
    brand: 'Nike',
    type: 'Low-top',
    themes: ['Tamil Culture', 'Minimalist'],
    imageUrl: 'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=600&q=80',
    aspectRatio: 'wide',
    tags: ['white', 'kolam', 'minimal'],
    featured: true,
  },
  {
    id: '7',
    name: 'Retro Sk8-Hi',
    brand: 'Vans',
    type: 'High-top',
    themes: ['Retro', 'Graffiti'],
    imageUrl: 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=600&q=80',
    aspectRatio: 'tall',
    tags: ['checkerboard', 'retro', 'skate'],
    featured: false,
  },
  {
    id: '8',
    name: 'Nature Trail',
    brand: 'New Balance',
    type: 'Mid-top',
    themes: ['Nature', 'Abstract'],
    imageUrl: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=600&q=80',
    aspectRatio: 'square',
    tags: ['green', 'earth', 'nature'],
    featured: false,
  },
  {
    id: '9',
    name: 'Classic Superstar',
    brand: 'Adidas',
    type: 'Low-top',
    themes: ['Vintage', 'Minimalist'],
    imageUrl: 'https://images.unsplash.com/photo-1518002054494-3a6f94352e9d?w=600&q=80',
    aspectRatio: 'wide',
    tags: ['white', 'shell toe', 'classic'],
    featured: false,
  },
  {
    id: '10',
    name: 'Puma Street',
    brand: 'Puma',
    type: 'Low-top',
    themes: ['Streetwear', 'Abstract'],
    imageUrl: 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=600&q=80',
    aspectRatio: 'tall',
    tags: ['black', 'street', 'sleek'],
    featured: false,
  },
  {
    id: '11',
    name: 'Reebok Heritage',
    brand: 'Reebok',
    type: 'Low-top',
    themes: ['Vintage', 'Retro'],
    imageUrl: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=600&q=80',
    aspectRatio: 'square',
    tags: ['white', 'heritage', 'classic'],
    featured: false,
  },
  {
    id: '12',
    name: 'Dunk Batik',
    brand: 'Nike',
    type: 'Low-top',
    themes: ['Tamil Culture', 'Floral'],
    imageUrl: 'https://images.unsplash.com/photo-1584735175315-9d5df23be620?w=600&q=80',
    aspectRatio: 'tall',
    tags: ['batik', 'pattern', 'custom'],
    featured: true,
  },
  {
    id: '13',
    name: 'Slip Splash',
    brand: 'Vans',
    type: 'Slip-on',
    themes: ['Abstract', 'Graffiti'],
    imageUrl: 'https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=600&q=80',
    aspectRatio: 'wide',
    tags: ['colorful', 'slip-on', 'paint'],
    featured: false,
  },
  {
    id: '14',
    name: 'Jordan Lotus',
    brand: 'Jordan',
    type: 'Mid-top',
    themes: ['Floral', 'Tamil Culture'],
    imageUrl: 'https://images.unsplash.com/photo-1600269452121-4f2416e55c28?w=600&q=80',
    aspectRatio: 'tall',
    tags: ['lotus', 'gold', 'temple'],
    featured: true,
  },
  {
    id: '15',
    name: 'Minimal Boot',
    brand: 'Puma',
    type: 'Boot',
    themes: ['Minimalist', 'Streetwear'],
    imageUrl: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600&q=80',
    aspectRatio: 'square',
    tags: ['black', 'boot', 'minimal'],
    featured: false,
  },
];

export const ALL_BRANDS = [...new Set(MOCK_SHOES.map((s) => s.brand))].sort();
export const ALL_TYPES = [...new Set(MOCK_SHOES.map((s) => s.type))].sort();
export const ALL_THEMES = [...new Set(MOCK_SHOES.flatMap((s) => s.themes))].sort();
